spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/l_s_m_s
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: ${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}

  jackson:
    property-naming-strategy: SNAKE_CASE

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET}
  accessExpirationMs: ${JWT_ACCESS_EXPIRATION_MS:900000}
  refreshExpirationMs: ${JWT_REFRESH_EXPIRATION_MS:604800000}

server:
  port: ${SERVER_PORT:8081}
